# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    env:
      node-vesion: 16.x

    steps:
    - uses: actions/checkout@v3
    - name: Setup pnpm
      # You may pin to the exact commit or the version.
      # uses: pnpm/action-setup@10693b3829bf86eb2572aef5f3571dcf5ca9287d
      uses: pnpm/action-setup@v2
#     - name: Use Node.js ${{ matrix.node-version }}
    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v3
      with:
#         node-version: ${{ matrix.node-version }}
        node-version: ${{ env.node-version }}
        registry-url: https://registry.npmjs.org/
        cache: 'pnpm'

    - name: workspace build
      run: pnpm -r install && pnpm --filter share build

    - name: Install
      run: pnpm install

    - name: TypeCheck
      run: pnpm run typecheck

  test:
    runs-on: ubuntu-latest
    env:
      node-vesion: 16.x
#     strategy:
#       matrix:
#         node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Setup pnpm
      # You may pin to the exact commit or the version.
      # uses: pnpm/action-setup@10693b3829bf86eb2572aef5f3571dcf5ca9287d
      uses: pnpm/action-setup@v2
#     - name: Use Node.js ${{ matrix.node-version }}
    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v3
      with:
#         node-version: ${{ matrix.node-version }}
        node-version: ${{ env.node-version }}
        registry-url: https://registry.npmjs.org/
        cache: 'pnpm'

    - name: Install
      run: pnpm install

    - name: Unit Test
      run: pnpm run test:unit

